version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      # Mount a volume for persistent model storage
      - model-data:/app/models
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=digit_recognizer
      - DB_USER=alice
      - DB_PASSWORD=inwonderland
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Add initialization script if needed
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=alice
      - POSTGRES_PASSWORD=inwonderland
      - POSTGRES_DB=digit_recognizer
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alice -d digit_recognizer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
  model-data: