services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - model-data:/app/models
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=digit_recognizer
      - DB_USER=alice
      - DB_PASSWORD=inwonderland
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alice
      - POSTGRES_PASSWORD=inwonderland
      - POSTGRES_DB=digit_recognizer
    restart: unless-stopped

volumes:
  postgres-data:
  model-data: